const fs = require('fs');

const rawCities = [
    {n: "Agra", d: "Home to the iconic Taj Mahal, a masterpiece of Mughal architecture.", b: "Taj Mahal", b_icon: "landmark"},
    {n: "Jaipur", d: "The Pink City, famous for its majestic forts, palaces, and vibrant culture.", b: "Amber Fort", b_icon: "landmark"},
    {n: "Goa", d: "A tropical paradise known for its pristine beaches, vibrant nightlife, and Portuguese heritage.", b: "Baga Beach", b_icon: "waves"},
    {n: "Munnar", d: "A serene hill station surrounded by rolling tea gardens and misty peaks.", b: "Tea Museum", b_icon: "coffee"},
    {n: "Udaipur", d: "The City of Lakes, offering romantic boat rides and magnificent palaces.", b: "City Palace", b_icon: "landmark"},
    {n: "Varanasi", d: "The spiritual heart of India, famous for its ancient temples and sacred ghats.", b: "Kashi Vishwanath Temple", b_icon: "landmark"},
    {n: "Delhi", d: "A bustling metropolis blending historic monuments with modern vibrancy.", b: "Red Fort", b_icon: "landmark"},
    {n: "Mumbai", d: "The City of Dreams, offering a mix of colonial architecture, beaches, and Bollywood.", b: "Gateway of India", b_icon: "landmark"},
    {n: "Kochi", d: "A coastal city famous for its Chinese fishing nets and historic spice markets.", b: "Fort Kochi", b_icon: "landmark"},
    {n: "Rishikesh", d: "The Yoga Capital of the World, offering spiritual retreats and river rafting.", b: "Lakshman Jhula", b_icon: "landmark"},
    {n: "Manali", d: "A breathtaking hill station known for adventure sports and snow-capped peaks.", b: "Solang Valley", b_icon: "tree-pine"},
    {n: "Shimla", d: "A charming colonial hill station with scenic views and historic architecture.", b: "The Ridge", b_icon: "landmark"},
    {n: "Darjeeling", d: "Famous for its world-class tea and panoramic views of the Himalayas.", b: "Tiger Hill", b_icon: "tree-pine"},
    {n: "Ooty", d: "The Queen of Hill Stations, known for its botanical gardens and toy train.", b: "Ooty Lake", b_icon: "waves"},
    {n: "Mysore", d: "A royal city known for its magnificent palace and rich cultural heritage.", b: "Mysore Palace", b_icon: "landmark"},
    {n: "Hyderabad", d: "The City of Pearls, offering a blend of historic monuments and legendary cuisine.", b: "Charminar", b_icon: "landmark"},
    {n: "Kolkata", d: "The Cultural Capital of India, known for its grand colonial architecture and sweets.", b: "Victoria Memorial", b_icon: "landmark"},
    {n: "Chennai", d: "A major cultural hub with beautiful temples, beaches, and South Indian traditions.", b: "Marina Beach", b_icon: "waves"},
    {n: "Pondicherry", d: "A peaceful coastal town with charming French colonial streets and spiritual ashrams.", b: "Auroville", b_icon: "landmark"},
    {n: "Hampi", d: "A UNESCO World Heritage site with fascinating ruins of the Vijayanagara Empire.", b: "Virupaksha Temple", b_icon: "landmark"},
    {n: "Andaman Islands", d: "A tropical archipelago known for its crystal-clear waters and vibrant coral reefs.", b: "Radhanagar Beach", b_icon: "waves"},
    {n: "Srinagar", d: "A paradise on earth, famous for its houseboats and stunning Mughal gardens.", b: "Dal Lake", b_icon: "waves"},
    {n: "Leh", d: "A high-altitude desert city known for its breathtaking landscapes and Buddhist monasteries.", b: "Pangong Lake", b_icon: "waves"},
    {n: "Amritsar", d: "Home to the Golden Temple, the spiritual and cultural center of the Sikh religion.", b: "Golden Temple", b_icon: "landmark"},
    {n: "Jaisalmer", d: "The Golden City, famous for its yellow sandstone architecture and desert safaris.", b: "Jaisalmer Fort", b_icon: "landmark"},
    {n: "Jodhpur", d: "The Blue City, overlooked by the magnificent Mehrangarh Fort.", b: "Mehrangarh Fort", b_icon: "landmark"},
    {n: "Pushkar", d: "A holy city built around a sacred lake, famous for its annual camel fair.", b: "Pushkar Lake", b_icon: "waves"},
    {n: "Khajuraho", d: "Renowned for its group of ancient temples featuring exquisite and intricate carvings.", b: "Kandariya Mahadeva Temple", b_icon: "landmark"},
    {n: "Alleppey", d: "The Venice of the East, famous for its serene backwaters and houseboat cruises.", b: "Backwaters", b_icon: "waves"},
    {n: "Gokarna", d: "A relaxed coastal town known for its pristine beaches and sacred temples.", b: "Om Beach", b_icon: "waves"},
    {n: "Madurai", d: "An ancient city centered around the brilliantly carved Meenakshi Amman Temple.", b: "Meenakshi Temple", b_icon: "landmark"},
    {n: "Kanyakumari", d: "The southernmost tip of India, where three major water bodies meet.", b: "Vivekananda Rock Memorial", b_icon: "landmark"},
    {n: "Ranthambore", d: "A premier national park offering excellent chances of spotting Royal Bengal tigers.", b: "Ranthambore Fort", b_icon: "landmark"},
    {n: "Jim Corbett", d: "India's oldest national park, famous for its rich wildlife and scenic landscapes.", b: "Dhikala Zone", b_icon: "tree-pine"},
    {n: "Nainital", d: "A picturesque hill station centered around a beautiful, eye-shaped lake.", b: "Naini Lake", b_icon: "waves"},
    {n: "Mussoorie", d: "The Queen of the Hills, offering stunning views of the Doon Valley.", b: "Kempty Falls", b_icon: "waves"},
    {n: "Coorg", d: "The Scotland of India, known for its lush coffee estates and misty hills.", b: "Abbey Falls", b_icon: "waves"},
    {n: "Wayanad", d: "A lush, green district offering waterfalls, caves, and abundant wildlife.", b: "Edakkal Caves", b_icon: "landmark"},
    {n: "Mahabaleshwar", d: "A popular hill station known for its strawberry farms and panoramic viewpoints.", b: "Arthur's Seat", b_icon: "tree-pine"},
    {n: "Lonavala", d: "A scenic retreat in the Sahyadri mountains, famous for its lush valleys and caves.", b: "Tiger's Leap", b_icon: "tree-pine"},
    {n: "Pune", d: "The Oxford of the East, blending historic Maratha forts with a vibrant youth culture.", b: "Shaniwar Wada", b_icon: "landmark"},
    {n: "Aurangabad", d: "A historical city serving as the gateway to the magnificent Ajanta and Ellora Caves.", b: "Ellora Caves", b_icon: "landmark"},
    {n: "Ahmedabad", d: "India's first UNESCO World Heritage City, known for its rich history and textiles.", b: "Sabarmati Ashram", b_icon: "landmark"},
    {n: "Kutch", d: "A vast white salt desert offering breathtaking landscapes and vibrant local crafts.", b: "Rann of Kutch", b_icon: "tree-pine"},
    {n: "Dwarka", d: "An ancient and sacred city associated with Lord Krishna, located on the Arabian Sea.", b: "Dwarkadhish Temple", b_icon: "landmark"},
    {n: "Somnath", d: "Home to the revered Somnath Temple, a major pilgrimage site by the sea.", b: "Somnath Temple", b_icon: "landmark"},
    {n: "Gwalior", d: "A historic city dominated by a massive hill fort and rich musical heritage.", b: "Gwalior Fort", b_icon: "landmark"},
    {n: "Orchha", d: "A medieval town featuring stunning palaces and temples along the Betwa River.", b: "Orchha Fort", b_icon: "landmark"},
    {n: "Bhopal", d: "The City of Lakes, boasting a mix of historic mosques and beautiful water bodies.", b: "Upper Lake", b_icon: "waves"},
    {n: "Indore", d: "A vibrant city famous for its bustling street food markets and rich Maratha history.", b: "Rajwada Palace", b_icon: "landmark"},
    {n: "Puri", d: "A coastal city known for the revered Jagannath Temple and long sandy beaches.", b: "Jagannath Temple", b_icon: "landmark"},
    {n: "Bhubaneswar", d: "The Temple City of India, featuring hundreds of ancient sandstone temples.", b: "Lingaraja Temple", b_icon: "landmark"},
    {n: "Konark", d: "Home to the architectural marvel of the Sun Temple, built in the shape of a chariot.", b: "Sun Temple", b_icon: "landmark"},
    {n: "Guwahati", d: "The gateway to Northeast India, located on the banks of the mighty Brahmaputra River.", b: "Kamakhya Temple", b_icon: "landmark"},
    {n: "Shillong", d: "The Scotland of the East, offering rolling hills, waterfalls, and a pleasant climate.", b: "Umiam Lake", b_icon: "waves"},
    {n: "Cherrapunji", d: "One of the wettest places on earth, known for its living root bridges and waterfalls.", b: "Living Root Bridges", b_icon: "tree-pine"},
    {n: "Tawang", d: "A scenic Himalayan town famous for its large Buddhist monastery and high passes.", b: "Tawang Monastery", b_icon: "landmark"},
    {n: "Gangtok", d: "A beautiful hill station offering stunning views of Mount Kanchenjunga.", b: "Nathu La Pass", b_icon: "tree-pine"},
    {n: "Pelling", d: "A tranquil town in Sikkim with spectacular views of the Himalayan ranges.", b: "Pemayangtse Monastery", b_icon: "landmark"},
    {n: "Kaziranga", d: "A famous national park known for its population of one-horned rhinoceroses.", b: "Kaziranga National Park", b_icon: "tree-pine"},
    {n: "Dharamshala", d: "The serene residence of the Dalai Lama, blending Tibetan culture with Himalayan beauty.", b: "Tsuglagkhang Complex", b_icon: "landmark"},
    {n: "Dalhousie", d: "A charming hill station retaining its old-world colonial charm and architecture.", b: "Khajjiar", b_icon: "tree-pine"},
    {n: "Spiti Valley", d: "A rugged and remote high-altitude desert known for its stunning stark landscapes.", b: "Key Monastery", b_icon: "landmark"},
    {n: "Rameswaram", d: "A sacred island town famous for its grand temple and mythological significance.", b: "Ramanathaswamy Temple", b_icon: "landmark"},
    {n: "Thanjavur", d: "The cultural heartland of Tamil Nadu, home to the magnificent Brihadeeswara Temple.", b: "Brihadeeswara Temple", b_icon: "landmark"},
    {n: "Kodaikanal", d: "The Princess of Hill Stations, offering misty mountains and a beautiful star-shaped lake.", b: "Kodaikanal Lake", b_icon: "waves"},
    {n: "Matheran", d: "An eco-friendly, automobile-free hill station near Mumbai.", b: "Echo Point", b_icon: "tree-pine"},
    {n: "Auli", d: "A premier ski destination offering panoramic views of the Nanda Devi peak.", b: "Auli Ropeway", b_icon: "tree-pine"},
    {n: "Kedarnath", d: "A deeply revered Hindu pilgrimage site located in the majestic Garhwal Himalayas.", b: "Kedarnath Temple", b_icon: "landmark"},
    {n: "Badrinath", d: "One of the most important pilgrimage sites in India, nestled among snowy peaks.", b: "Badrinath Temple", b_icon: "landmark"},
    {n: "Haridwar", d: "A holy city where the Ganges emerges from the Himalayas, known for its evening aarti.", b: "Har Ki Pauri", b_icon: "landmark"},
    {n: "Mathura", d: "The revered birthplace of Lord Krishna, dotted with numerous temples and ghats.", b: "Shri Krishna Janmasthan", b_icon: "landmark"},
    {n: "Vrindavan", d: "A spiritual town closely associated with the childhood of Lord Krishna.", b: "Banke Bihari Temple", b_icon: "landmark"},
    {n: "Ayodhya", d: "A deeply spiritual city renowned as the birthplace of Lord Rama.", b: "Ram Janmabhoomi", b_icon: "landmark"},
    {n: "Prayagraj", d: "A holy city marking the magnificent confluence of three sacred rivers.", b: "Triveni Sangam", b_icon: "waves"},
    {n: "Gaya", d: "A significant pilgrimage site where Buddha attained enlightenment.", b: "Mahabodhi Temple", b_icon: "landmark"},
    {n: "Nalanda", d: "The site of one of the world's oldest and most prestigious ancient universities.", b: "Nalanda Ruins", b_icon: "landmark"},
    {n: "Rajgir", d: "An ancient city with spiritual significance for both Buddhists and Jains.", b: "Vishwa Shanti Stupa", b_icon: "landmark"},
    {n: "Sarnath", d: "A peaceful deer park where Lord Buddha gave his first sermon.", b: "Dhamek Stupa", b_icon: "landmark"},
    {n: "Mawlynnong", d: "Often referred to as Asia's cleanest village, located in picturesque Meghalaya.", b: "Living Root Bridge", b_icon: "tree-pine"},
    {n: "Ziro", d: "A lush green valley in Arunachal Pradesh, famous for its unique tribal culture and music.", b: "Ziro Valley", b_icon: "tree-pine"},
    {n: "Majuli", d: "The world's largest river island, known for its neo-Vaishnavite culture.", b: "Kamalabari Satra", b_icon: "landmark"},
    {n: "Havelock Island", d: "A beautiful island offering pristine beaches and world-class scuba diving.", b: "Elephant Beach", b_icon: "waves"},
    {n: "Neil Island", d: "A tranquil island with white sandy beaches and excellent snorkeling spots.", b: "Bharatpur Beach", b_icon: "waves"},
    {n: "Lakshadweep", d: "An untouched archipelago of coral reefs, clear waters, and serene beaches.", b: "Agatti Island", b_icon: "waves"},
    {n: "Chopta", d: "Often called the Mini Switzerland of India, known for its lush meadows.", b: "Tungnath Temple", b_icon: "landmark"},
    {n: "Mount Abu", d: "The only hill station in Rajasthan, famous for its intricately carved Jain temples.", b: "Dilwara Temples", b_icon: "landmark"},
    {n: "Bikaner", d: "A desert city known for its impressive fort, vibrant culture, and savory snacks.", b: "Junagarh Fort", b_icon: "landmark"},
    {n: "Chittorgarh", d: "Home to India's largest fort, echoing tales of Rajput valor and history.", b: "Chittorgarh Fort", b_icon: "landmark"},
    {n: "Kumarakom", d: "A serene village on Vembanad Lake, famous for its backwater tourism and bird sanctuary.", b: "Kumarakom Bird Sanctuary", b_icon: "tree-pine"},
    {n: "Kovalam", d: "An internationally renowned beach town with three adjacent crescent beaches.", b: "Lighthouse Beach", b_icon: "waves"},
    {n: "Varkala", d: "A unique coastal town where laterite cliffs drop dramatically into the Arabian Sea.", b: "Varkala Cliff", b_icon: "waves"},
    {n: "Thrissur", d: "The cultural capital of Kerala, known for its spectacular temple festivals.", b: "Vadakkunnathan Temple", b_icon: "landmark"},
    {n: "Belur", d: "An ancient temple town renowned for the exquisite Hoysala architecture.", b: "Chennakeshava Temple", b_icon: "landmark"},
    {n: "Halebidu", d: "The former capital of the Hoysala Empire, showcasing beautifully ruined temples.", b: "Hoysaleswara Temple", b_icon: "landmark"},
    {n: "Badami", d: "Famous for its magnificent rock-cut structural temples and red sandstone cliffs.", b: "Badami Cave Temples", b_icon: "landmark"},
    {n: "Pattadakal", d: "A UNESCO World Heritage site known for its harmonious blend of architectural styles.", b: "Group of Monuments", b_icon: "landmark"},
    {n: "Vijayawada", d: "A bustling city on the Krishna River, famous for the Kanaka Durga Temple.", b: "Kanaka Durga Temple", b_icon: "landmark"},
    {n: "Tirupati", d: "A major pilgrimage city, home to the incredibly wealthy and revered Venkateswara Temple.", b: "Sri Venkateswara Temple", b_icon: "landmark"},
    {n: "Visakhapatnam", d: "A coastal city blending beautiful beaches with lush eastern ghats.", b: "Rushikonda Beach", b_icon: "waves"},
    {n: "Ranchi", d: "The City of Waterfalls, offering scenic natural beauty and tribal culture.", b: "Dassam Falls", b_icon: "waves"},
    {n: "Patna", d: "An ancient city on the Ganges with deep historical and political roots.", b: "Golghar", b_icon: "landmark"},
    {n: "Bodh Gaya", d: "One of the most sacred Buddhist pilgrimage centers in the world.", b: "Mahabodhi Temple", b_icon: "landmark"},
    {n: "Surat", d: "The Diamond City of India, famous for its textiles and vibrant street food.", b: "Dumas Beach", b_icon: "waves"},
    {n: "Vadodara", d: "A cultural city known for its magnificent palaces and educational institutions.", b: "Laxmi Vilas Palace", b_icon: "landmark"},
    {n: "Rajkot", d: "A bustling city with a rich historical background related to Mahatma Gandhi.", b: "Kaba Gandhi No Delo", b_icon: "landmark"},
    {n: "Gandhinagar", d: "The green capital city of Gujarat, famous for the Akshardham Temple.", b: "Akshardham Temple", b_icon: "landmark"},
    {n: "Chandigarh", d: "A modern planned city known for its unique architecture and urban design.", b: "Rock Garden", b_icon: "tree-pine"},
    {n: "Ludhiana", d: "An industrial hub with a rich cultural heritage and historical sites.", b: "Lodhi Fort", b_icon: "landmark"},
    {n: "Jalandhar", d: "An ancient city known for its sports industry and historical temples.", b: "Devi Talab Mandir", b_icon: "landmark"},
    {n: "Patiala", d: "Famous for its traditional turbans, peg, and royal palaces.", b: "Qila Mubarak", b_icon: "landmark"},
    {n: "Raipur", d: "The capital of Chhattisgarh, offering beautiful lakes and ancient temples.", b: "Swami Vivekanand Sarovar", b_icon: "waves"},
    {n: "Bhilai", d: "An industrial city known for its massive steel plant and peaceful vibe.", b: "Maitri Bagh", b_icon: "tree-pine"},
    {n: "Jamshedpur", d: "The Steel City, uniquely planned with lush green parks and lakes.", b: "Jubilee Park", b_icon: "tree-pine"},
    {n: "Dhanbad", d: "The Coal Capital of India, surrounded by scenic dams and hills.", b: "Maithon Dam", b_icon: "waves"},
    {n: "Dehradun", d: "A picturesque city in the Doon Valley, serving as a gateway to the mountains.", b: "Robber's Cave", b_icon: "tree-pine"},
    {n: "Rishikesh", d: "The Yoga Capital of the World, offering spiritual retreats and river rafting.", b: "Triveni Ghat", b_icon: "waves"},
    {n: "Jammu", d: "The Winter Capital of J&K, famous for its ancient temples and shrines.", b: "Raghunath Temple", b_icon: "landmark"},
    {n: "Gulmarg", d: "A stunning hill station known for its world-class skiing and gondola ride.", b: "Gulmarg Gondola", b_icon: "tree-pine"},
    {n: "Pahalgam", d: "A breathtaking valley known for its lush meadows and the Lidder River.", b: "Betaab Valley", b_icon: "tree-pine"},
    {n: "Sonamarg", d: "The Meadow of Gold, offering spectacular glaciers and mountain lakes.", b: "Thajiwas Glacier", b_icon: "tree-pine"},
    {n: "Kargil", d: "A historic town with stunning landscapes along the Suru River.", b: "Kargil War Memorial", b_icon: "landmark"},
    {n: "Siliguri", d: "A bustling city serving as the gateway to North East India.", b: "Mahananda Wildlife Sanctuary", b_icon: "tree-pine"},
    {n: "Darjeeling", d: "Famous for its world-class tea and panoramic views of the Himalayas.", b: "Tiger Hill", b_icon: "tree-pine"},
    {n: "Kalimpong", d: "A quiet hill station known for its colonial architecture and Buddhist monasteries.", b: "Durpin Monastery", b_icon: "landmark"},
    {n: "Mirik", d: "A serene tourist spot nestled in the hills, centered around a beautiful lake.", b: "Sumendu Lake", b_icon: "waves"},
    {n: "Digha", d: "A popular coastal resort town known for its wide and flat beaches.", b: "New Digha Beach", b_icon: "waves"},
    {n: "Mandarmoni", d: "A rapidly developing seaside resort village offering a long driveable beach.", b: "Mandarmoni Beach", b_icon: "waves"},
    {n: "Sundarbans", d: "The largest mangrove forest in the world, home to the Royal Bengal Tiger.", b: "Sajnekhali Bird Sanctuary", b_icon: "tree-pine"},
    {n: "Bikaner", d: "A desert city known for its impressive fort, vibrant culture, and savory snacks.", b: "Junagarh Fort", b_icon: "landmark"}
];

const processed = rawCities.map((c, i) => {
    return {
        id: c.n.toLowerCase().replace(/\s+/g, '-'),
        name: c.n,
        icon: c.b_icon === 'waves' ? 'waves' : (c.b_icon === 'tree-pine' ? 'tree-pine' : 'map-pin'),
        dayOffset: 0,
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=' + encodeURIComponent(c.n + ' India'),
        notes: c.d,
        beats: [
            {
                title: c.b,
                icon: c.b_icon,
                where: c.b + ', ' + c.n,
                mapsUrl: 'https://www.google.com/maps/search/?api=1&query=' + encodeURIComponent(c.b + ' ' + c.n),
                notes: 'Must-visit spot in ' + c.n,
                hour: 10,
                intent: ['spiritual', 'cultural', 'adventure', 'culinary'],
                faith: ['any'],
                party: ['any'],
                pace: ['standard'],
                mobility: 'easy'
            }
        ]
    };
});

const fileContent = 'window.KYT_CITIES = ' + JSON.stringify(processed, null, 2) + ';';
fs.writeFileSync('data/cities.js', fileContent);

console.log('Generated ' + processed.length + ' cities.');
