// scripts/city_aliases.js
module.exports = {
  "agra": ["Taj City", "Akbarabad"],
  "jaipur": ["Pink City"],
  "goa": ["Panaji", "North Goa", "South Goa"],
  "munnar": [],
  "udaipur": ["City of Lakes", "Mewar"],
  "varanasi": ["Kashi", "Banaras", "Benares"],
  "delhi": ["New Delhi", "Dilli", "NCR"],
  "mumbai": ["Bombay"],
  "kochi": ["Cochin", "Ernakulam"],
  "rishikesh": ["Hrishikesh"],
  "manali": ["Kullu Manali"],
  "shimla": ["Simla"],
  "darjeeling": ["Queen of the Hills"],
  "ooty": ["Udhagamandalam", "Ootacamund"],
  "mysore": ["Mysuru"],
  "hyderabad": ["City of Pearls", "Bhagyanagar", "Secunderabad"],
  "kolkata": ["Calcutta"],
  "chennai": ["Madras"],
  "pondicherry": ["Puducherry", "Pondy"],
  "hampi": ["Vijayanagara", "Kishkindha"],
  "andaman-islands": ["Port Blair", "Andaman", "Andamans"],
  "srinagar": ["Kashmir Valley"],
  "leh": ["Ladakh"],
  "amritsar": ["Ambarsar", "Ramdaspur"],
  "jaisalmer": ["Golden City"],
  "jodhpur": ["Blue City", "Sun City", "Marwar"],
  "pushkar": ["Tirth Raj"],
  "khajuraho": [],
  "alleppey": ["Alappuzha", "Venice of the East"],
  "gokarna": [],
  "madurai": ["Thoonga Nagaram", "Athens of the East", "Temple City"],
  "kanyakumari": ["Cape Comorin"],
  "ranthambore": ["Sawai Madhopur"],
  "jim-corbett": ["Corbett", "Ramnagar"],
  "nainital": ["Lake District"],
  "mussoorie": ["Queen of the Hills", "Landour"],
  "coorg": ["Kodagu", "Madikeri", "Scotland of India"],
  "wayanad": ["Kalpetta", "Sulthan Bathery"],
  "mahabaleshwar": ["Mahableshwar"],
  "lonavala": ["Lonavla", "Khandala"],
  "pune": ["Poona", "Punyanagari"],
  "aurangabad": ["Chhatrapati Sambhaji Nagar", "Sambhaji Nagar", "Sambhajinagar"],
  "ahmedabad": ["Amdavad", "Karnavati"],
  "kutch": ["Rann of Kutch", "Bhuj", "Kachchh"],
  "dwarka": ["Dwarkapuri", "Dwaraka"],
  "somnath": ["Prabhas Patan"],
  "gwalior": ["Gopachal"],
  "orchha": ["Urchha"],
  "bhopal": ["City of Lakes", "Bhojpal"],
  "indore": ["Ahilyanagari", "Mini Mumbai"],
  "puri": ["Jagannath Puri", "Purushottama Kshetra", "Srikshetra"],
  "bhubaneswar": ["Temple City", "Ekamra Kshetra"],
  "konark": ["Arka Kshetra", "Black Pagoda"],
  "guwahati": ["Gauhati", "Pragjyotishpura"],
  "shillong": ["Scotland of the East"],
  "cherrapunji": ["Sohra"],
  "tawang": [],
  "gangtok": [],
  "pelling": [],
  "kaziranga": [],
  "dharamshala": ["McLeod Ganj", "Mcleodganj", "Bhagsu", "Kangra"],
  "dalhousie": ["Khajjiar"],
  "spiti-valley": ["Spiti", "Kaza"],
  "rameswaram": ["Rameshwaram"],
  "thanjavur": ["Tanjore"],
  "kodaikanal": ["Kodai", "Princess of Hill Stations"],
  "matheran": ["Karjat Hills"],
  "auli": ["Joshimath"],
  "kedarnath": ["Kedar"],
  "badrinath": ["Badri Vishal", "Badrikashram"],
  "haridwar": ["Hardwar", "Mayapuri", "Gangadwara"],
  "mathura": ["Braj", "Brajbhoomi", "Muttra"],
  "vrindavan": ["Brindavan", "Braj"],
  "ayodhya": ["Faizabad", "Saket", "Ram Janmabhoomi"],
  "prayagraj": ["Allahabad", "Ilahabad", "Triveni Sangam", "Prayag"],
  "gaya": ["Gaya Ji"],
  "nalanda": [],
  "rajgir": ["Rajagriha"],
  "sarnath": ["Isipatana", "Mrigadava"],
  "mawlynnong": ["Cleanest Village"],
  "ziro": ["Ziro Valley", "Apatani Valley"],
  "majuli": [],
  "havelock-island": ["Swaraj Dweep", "Havelock"],
  "neil-island": ["Shaheed Dweep", "Neil"],
  "lakshadweep": ["Laccadive", "Agatti"],
  "chopta": ["Tungnath", "Mini Switzerland"],
  "mount-abu": ["Abu"],
  "bikaner": ["Camel City"],
  "chittorgarh": ["Chittor"],
  "kumarakom": ["Vembanad"],
  "kovalam": ["Thiruvananthapuram", "Trivandrum"],
  "varkala": ["Papanasam"],
  "thrissur": ["Trichur"],
  "belur": ["Velapuri"],
  "halebidu": ["Dorasamudra", "Halebeedu"],
  "badami": ["Vatapi"],
  "pattadakal": ["Raktapura", "Pattadakallu"],
  "vijayawada": ["Bezawada", "Blazewada"],
  "tirupati": ["Tirumala", "Balaji", "Venkatachala"],
  "visakhapatnam": ["Vizag", "Waltair"],
  "ranchi": ["City of Waterfalls"],
  "patna": ["Pataliputra", "Patliputra", "Azimabad"],
  "bodh-gaya": ["Bodhgaya", "Uruvela"],
  "surat": ["Diamond City", "Suryapur"],
  "vadodara": ["Baroda", "Sayajinagari"],
  "rajkot": [],
  "gandhinagar": [],
  "chandigarh": ["The City Beautiful"],
  "ludhiana": [],
  "jalandhar": ["Jullundur"],
  "patiala": ["Royal City"],
  "raipur": [],
  "bhilai": ["Steel City"],
  "jamshedpur": ["Tatanagar", "Steel City"],
  "dhanbad": ["Coal Capital"],
  "dehradun": ["Doon"],
  "jammu": ["City of Temples"],
  "gulmarg": ["Meadow of Flowers"],
  "pahalgam": ["Valley of Shepherds"],
  "sonamarg": ["Meadow of Gold"],
  "kargil": ["Drass", "Suru"],
  "siliguri": ["Gateway to Northeast"],
  "kalimpong": [],
  "mirik": [],
  "digha": [],
  "mandarmoni": ["Mandarmoni Beach"],
  "sundarbans": ["Sunderbans"],
  "bengaluru": ["Bangalore", "Bengaluru City", "Garden City", "Silicon Valley of India"],
  "lucknow": ["Awadh", "Oudh", "City of Nawabs", "Lakhnau"],
  "shirdi": ["Sai Nagar", "Shirdi Sai Baba"],
  "kancheepuram": ["Kanchipuram", "Conjeevaram", "Kanchi", "City of Thousand Temples"]
};
